In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:

import pandas as pd

In [5]:
restaurant=pd.read_csv("restaurant_data.csv")
print(restaurant.head())

           Name  Location   Cuisine  Rating  Seating Capacity  \
0  Restaurant 0     Rural  Japanese     4.0                38
1  Restaurant 1  Downtown   Mexican     3.2                76
2  Restaurant 2     Rural   Italian     4.7                48
3  Restaurant 3     Rural   Italian     4.4                34
4  Restaurant 4  Downtown  Japanese     4.9                88

   Average Meal Price  Marketing Budget  Social Media Followers  \
0               73.98              2224                   23406
1               28.11              4416                   42741
2               48.29              2796                   37285
3               51.55              1167                   15214
4               75.98              3639                   40171

   Chef Experience Years  Number of Reviews  Avg Review Length  \
0                     13                185         161.924906
1                      8                533         148.759717
2                     18                853          56.849189
3                     13                 82         205.433265
4                      9                 78         241.681584

   Ambience Score  Service Quality Score Parking Availability  \
0             1.3                    7.0                  Yes
1             2.6                    3.4                  Yes
2             5.3                    6.7                   No
3             4.6                    2.8                  Yes
4             8.6                    2.1                   No

   Weekend Reservations  Weekday Reservations     Revenue
0                    13                     4   638945.52
1                    48                     6   490207.83
2                    27                    14   541368.62
3                     9                    17   404556.80
4                    37                    26  1491046.35

In [6]:
column=restaurant.columns
print(column)

Index(['Name', 'Location', 'Cuisine', 'Rating', 'Seating Capacity',
       'Average Meal Price', 'Marketing Budget', 'Social Media Followers',
       'Chef Experience Years', 'Number of Reviews', 'Avg Review Length',
       'Ambience Score', 'Service Quality Score', 'Parking Availability',
       'Weekend Reservations', 'Weekday Reservations', 'Revenue'],
      dtype='object')

In [7]:
datatypes=restaurant.dtypes
print(datatypes)

Name                       object
Location                   object
Cuisine                    object
Rating                    float64
Seating Capacity            int64
Average Meal Price        float64
Marketing Budget            int64
Social Media Followers      int64
Chef Experience Years       int64
Number of Reviews           int64
Avg Review Length         float64
Ambience Score            float64
Service Quality Score     float64
Parking Availability       object
Weekend Reservations        int64
Weekday Reservations        int64
Revenue                   float64
dtype: object

In [8]:
restaurant.describe()

,Rating,Seating Capacity,Average Meal Price,Marketing Budget,Social Media Followers,Chef Experience Years,Number of Reviews,Avg Review Length,Ambience Score,Service Quality Score,Weekend Reservations,Weekday Reservations,Revenue
count,8368.000000,8368.000000,8368.000000,8368.000000,8368.000000,8368.000000,8368.000000,8368.000000,8368.000000,8368.000000,8368.000000,8368.000000,8.368000e+03
mean,4.008258,60.212835,47.896659,3218.254900,36190.621773,10.051984,523.010397,174.769974,5.521283,5.508772,29.491754,29.235301,6.560706e+05
std,0.581474,17.399488,14.336767,1824.896053,18630.153330,5.516606,277.215127,71.998060,2.575442,2.586552,20.025415,20.004277,2.674137e+05
min,3.000000,30.000000,25.000000,604.000000,5277.000000,1.000000,50.000000,50.011717,1.000000,1.000000,0.000000,0.000000,1.847085e+05
25%,3.500000,45.000000,35.490000,1889.000000,22592.500000,5.000000,277.000000,113.311102,3.300000,3.200000,13.000000,13.000000,4.546514e+05
50%,4.000000,60.000000,45.535000,2846.500000,32518.500000,10.000000,528.000000,173.910079,5.500000,5.600000,27.000000,26.000000,6.042421e+05
75%,4.500000,75.000000,60.300000,4008.500000,44566.250000,15.000000,764.250000,237.406885,7.800000,7.800000,43.000000,43.000000,8.130942e+05
max,5.000000,90.000000,76.000000,9978.000000,103777.000000,19.000000,999.000000,299.984924,10.000000,10.000000,88.000000,88.000000,1.531868e+06

This Dataset contains totally 17 columns with integer,float and char data types namely Name,
Location,
Cuisine,
Rating,
Seating Capacity,
Average Meal Price,
Marketing Budget,
Social Media Followers,
Chef Experience Years,
Number of Reviews,
Avg Review Length,
Ambience Score ,Service Quality Score,
Parking Availability,
Weekend Reservations,
Weekday Reservations,
Revenue.